// Firstly setting up basic  react app folder for our admin dashboard project and also celan my project from unneccessary default code after it as i am using shadcn so install tailwind css and types of node also for shadcn installation for more assistance we can go to shadcn documentation and also we can use tailwind css documentation for more assistance i will add it from documentation of shadcn
// By the use of shacn i have copied the code of login signup and dashboard after it i have make layout of dashboard bcz we want some things static in diff pages and only middle inventory must be changing so for this i wil make a layout and the things that remain same will be kept in layout and the things that must be changed will be kept in diff comp and after i make the use of Outlet
// which help in changing the middle part of the layout and the layout will remain same and the middle part will be changed for it we have to change in our router.tsx file and add children field in the / route so that we will have acess to diff pages and we can change the middle part of the layout

// one new thing as wee see in out login and signup we will not have anything in common so we will make a layout with nothing in it just Outlet of react router dom and we will use this layout for login and signup in router.tsx
//After it i will leanr about the useNavigate hook of react-router-dom which is used to navigate to diff pages in react and i will use it in my login page to navigate to home page after successful login and also i will learn about the useMutation hook of react-query which is used t make server calls along with the axios instance and i will use it in my login page to make a server call to login the user and after successful login i will navigate to home page
//if we want to send data to the server in this case we will use useMutation hook of react-query and we will pass the data to the mutate function of the useMutation hook and it will make a server call to the server and if we want to get some data from server in this case useQuery hook of react-query will be used and we will pass the url to the useQuery hook and it will make a server call to the server and get the data from the server
//After it i will leanrn about adding the loader into my app for it i wil get the lucid-react icon for loader and use mutate.ispending function of useMutation hook of react-query to show the loader when the server call is in progress

//After it i have learned about storing token and manage the state using zustand for this firstly i have to make  a zustand store using create method and in this store  i have 2 fields token and setToken and i have used devtools and persist middleware of zustand to store the token in the local storage so that after reload my token will not lost but it will b stored in local storage and then use it where i want authentication and authorization  i have implement this funct in login page
